# Generated by Django 2.2.1 on 2019-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=30)),
                ('borrowtime', models.DateTimeField(auto_now_add=True)),
                ('stu_id', models.CharField(max_length=10)),
                ('stu_name', models.CharField(max_length=15)),
                ('stu_phone', models.CharField(max_length=11)),
                ('stu_qq', models.CharField(max_length=15)),
            ],
        ),
    ]
