# Generated by Django 2.1.7 on 2019-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbooks',
            name='b_name',
            field=models.CharField(max_length=30, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='borrowbooks',
            name='borrowtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='borrowbooks',
            name='stu_id',
            field=models.CharField(max_length=10, verbose_name='校园卡号'),
        ),
        migrations.AlterField(
            model_name='borrowbooks',
            name='stu_name',
            field=models.CharField(max_length=15, verbose_name='借阅者姓名'),
        ),
        migrations.AlterField(
            model_name='borrowbooks',
            name='stu_phone',
            field=models.CharField(max_length=11, verbose_name='借阅者手机号码'),
        ),
        migrations.AlterField(
            model_name='borrowbooks',
            name='stu_qq',
            field=models.CharField(max_length=15, verbose_name='借阅者QQ'),
        ),
    ]
