# Generated by Django 2.1.7 on 2019-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20191205_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50, verbose_name='书名')),
                ('b_img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
