# Generated by Django 2.1.7 on 2019-12-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_bookdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='b_img',
            field=models.ImageField(upload_to='img', verbose_name='书籍封面'),
        ),
    ]
