# Generated by Django 2.1.7 on 2019-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_bookdb_b_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='b_img',
            field=models.ImageField(upload_to='bookimg', verbose_name='书籍封面'),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='b_status',
            field=models.CharField(choices=[('未借出', 'Small'), ('已借出', 'Medium')], max_length=20, null=True, verbose_name='书籍状态'),
        ),
    ]
